export const GAME_CONFIG = {
    GAME_RESOLUTION: 32,
    ISLAND_COUNT: 3,
    SHOW_GRID: true,
    DEBUG: process.env.NODE_ENV === 'development',
    DEFAULT_SHIP_SPEED: 3,
    DEFAULT_SHIP_CANON_DISTANCE: 4,
    DEAD_SHIP_LIVING_TIME: 3000,
    DEFAULT_CANON_POWER: 20,
    ITEM_GENERATION_INTERVAL: 500,
    MAX_ITEMS: 15,
}